import { InventoryMovement } from '../types/InventoryMovement';

// Extended type for display purposes with additional fields
export interface ActivityDisplay extends InventoryMovement {
  item_name: string;
  from_location_name: string;
  to_location_name: string;
  user_name: string;
}

// Generate mock activities data
export const mockActivities: ActivityDisplay[] = [
  {
    id: '1',
    inventory_action: 'MOVE',
    item_id: 'item-001',
    item_name: 'A',
    product_id: 'prod-001',
    from_location_id: 'loc-b3',
    from_location_name: 'Shelf B3',
    to_location_id: 'loc-p5',
    to_location_name: 'Pallet 5',
    quantity: 10,
    performed_by: 'user-001',
    user_name: 'Sarah Chen',
    performed_at: '2026-01-28T10:34:00Z',
  },
  {
    id: '2',
    inventory_action: 'ADJUSTMENT',
    item_id: 'item-002',
    item_name: 'B',
    product_id: 'prod-002',
    from_location_id: 'loc-a1',
    from_location_name: 'Bin A1',
    to_location_id: 'loc-a1',
    to_location_name: 'Bin A1',
    quantity: -10,
    performed_by: 'user-002',
    user_name: 'Mike Johnson',
    note: 'Updated quantity: 15 → 5',
    performed_at: '2026-01-28T10:12:00Z',
  },
  {
    id: '3',
    inventory_action: 'MOVE',
    item_id: 'item-003',
    item_name: 'C',
    product_id: 'prod-003',
    from_location_id: 'loc-wh-a',
    from_location_name: 'Warehouse A',
    to_location_id: 'loc-wh-b',
    to_location_name: 'Warehouse B',
    quantity: 25,
    performed_by: 'user-003',
    user_name: 'Emily Rodriguez',
    note: 'Transferred to Warehouse B',
    performed_at: '2026-01-28T09:58:00Z',
  },
  {
    id: '4',
    inventory_action: 'ADD',
    item_id: 'item-004',
    item_name: 'D',
    product_id: 'prod-004',
    from_location_id: 'loc-receiving',
    from_location_name: 'Receiving',
    to_location_id: 'loc-limbo',
    to_location_name: 'Limbo (QC pending)',
    quantity: 50,
    performed_by: 'user-004',
    user_name: 'David Park',
    note: 'Added to Limbo (QC pending)',
    performed_at: '2026-01-28T09:45:00Z',
  },
  {
    id: '5',
    inventory_action: 'ADD',
    item_id: 'item-005',
    item_name: 'E',
    product_id: 'prod-005',
    from_location_id: 'loc-supplier',
    from_location_name: 'Supplier X',
    to_location_id: 'loc-a2',
    to_location_name: 'Shelf A2',
    quantity: 100,
    performed_by: 'user-001',
    user_name: 'Sarah Chen',
    note: 'Restocked from Supplier X',
    performed_at: '2026-01-28T09:22:00Z',
  },
  {
    id: '6',
    inventory_action: 'MOVE',
    item_id: 'item-006',
    item_name: 'Notebooks (College Ruled)',
    product_id: 'prod-006',
    from_location_id: 'loc-c4',
    from_location_name: 'Shelf C4',
    to_location_id: 'loc-d1',
    to_location_name: 'Shelf D1',
    quantity: 30,
    performed_by: 'user-002',
    user_name: 'Mike Johnson',
    performed_at: '2026-01-28T09:10:00Z',
  },
  {
    id: '7',
    inventory_action: 'DISCARD',
    item_id: 'item-007',
    item_name: 'Markers (Dried Out)',
    product_id: 'prod-007',
    from_location_id: 'loc-e3',
    from_location_name: 'Bin E3',
    to_location_id: 'loc-waste',
    to_location_name: 'Waste',
    quantity: 12,
    performed_by: 'user-003',
    user_name: 'Emily Rodriguez',
    note: 'Damaged/expired items',
    performed_at: '2026-01-28T08:55:00Z',
  },
  {
    id: '8',
    inventory_action: 'CLOCKOUT',
    item_id: 'item-008',
    item_name: 'Scissors (5" Safety)',
    product_id: 'prod-008',
    from_location_id: 'loc-f2',
    from_location_name: 'Shelf F2',
    to_location_id: 'loc-checkout',
    to_location_name: 'Checkout',
    quantity: 20,
    performed_by: 'user-005',
    user_name: 'Amanda Liu',
    note: 'Order #12345',
    performed_at: '2026-01-28T08:30:00Z',
  },
  {
    id: '9',
    inventory_action: 'ADD',
    item_id: 'item-009',
    item_name: 'Erasers (Pink Pearl)',
    product_id: 'prod-009',
    from_location_id: 'loc-receiving',
    from_location_name: 'Receiving',
    to_location_id: 'loc-b1',
    to_location_name: 'Bin B1',
    quantity: 144,
    performed_by: 'user-004',
    user_name: 'David Park',
    performed_at: '2026-01-28T08:15:00Z',
  },
  {
    id: '10',
    inventory_action: 'ADJUSTMENT',
    item_id: 'item-010',
    item_name: 'Glue Sticks',
    product_id: 'prod-010',
    from_location_id: 'loc-a5',
    from_location_name: 'Shelf A5',
    to_location_id: 'loc-a5',
    to_location_name: 'Shelf A5',
    quantity: 5,
    performed_by: 'user-001',
    user_name: 'Sarah Chen',
    note: 'Count correction: 95 → 100',
    performed_at: '2026-01-28T08:00:00Z',
  },
  {
    id: '11',
    inventory_action: 'MOVE',
    item_id: 'item-011',
    item_name: 'Construction Paper',
    product_id: 'prod-011',
    from_location_id: 'loc-g3',
    from_location_name: 'Pallet 3',
    to_location_id: 'loc-h4',
    to_location_name: 'Shelf H4',
    quantity: 40,
    performed_by: 'user-006',
    user_name: 'James Wilson',
    performed_at: '2026-01-27T16:45:00Z',
  },
  {
    id: '12',
    inventory_action: 'CLOCKOUT',
    item_id: 'item-012',
    item_name: 'Pencils (#2)',
    product_id: 'prod-012',
    from_location_id: 'loc-d3',
    from_location_name: 'Bin D3',
    to_location_id: 'loc-checkout',
    to_location_name: 'Checkout',
    quantity: 288,
    performed_by: 'user-005',
    user_name: 'Amanda Liu',
    note: 'Order #12344',
    performed_at: '2026-01-27T16:20:00Z',
  },
  {
    id: '13',
    inventory_action: 'ADD',
    item_id: 'item-013',
    item_name: 'Rulers (12")',
    product_id: 'prod-013',
    from_location_id: 'loc-supplier',
    from_location_name: 'Supplier Y',
    to_location_id: 'loc-c2',
    to_location_name: 'Shelf C2',
    quantity: 60,
    performed_by: 'user-002',
    user_name: 'Mike Johnson',
    performed_at: '2026-01-27T15:50:00Z',
  },
  {
    id: '14',
    inventory_action: 'MOVE',
    item_id: 'item-014',
    item_name: 'Binders (1.5")',
    product_id: 'prod-014',
    from_location_id: 'loc-e5',
    from_location_name: 'Pallet 7',
    to_location_id: 'loc-f4',
    to_location_name: 'Shelf F4',
    quantity: 24,
    performed_by: 'user-003',
    user_name: 'Emily Rodriguez',
    performed_at: '2026-01-27T15:30:00Z',
  },
  {
    id: '15',
    inventory_action: 'ADJUSTMENT',
    item_id: 'item-015',
    item_name: 'Highlighters (Assorted)',
    product_id: 'prod-015',
    from_location_id: 'loc-b4',
    from_location_name: 'Bin B4',
    to_location_id: 'loc-b4',
    to_location_name: 'Bin B4',
    quantity: -8,
    performed_by: 'user-004',
    user_name: 'David Park',
    note: 'Inventory discrepancy correction',
    performed_at: '2026-01-27T15:00:00Z',
  },
  {
    id: '16',
    inventory_action: 'DISCARD',
    item_id: 'item-016',
    item_name: 'Crayons (Broken)',
    product_id: 'prod-016',
    from_location_id: 'loc-a3',
    from_location_name: 'Shelf A3',
    to_location_id: 'loc-waste',
    to_location_name: 'Waste',
    quantity: 15,
    performed_by: 'user-001',
    user_name: 'Sarah Chen',
    note: 'Damaged items removed',
    performed_at: '2026-01-27T14:30:00Z',
  },
  {
    id: '17',
    inventory_action: 'ADD',
    item_id: 'item-017',
    item_name: 'Folders (2-Pocket)',
    product_id: 'prod-017',
    from_location_id: 'loc-receiving',
    from_location_name: 'Receiving',
    to_location_id: 'loc-g2',
    to_location_name: 'Shelf G2',
    quantity: 120,
    performed_by: 'user-006',
    user_name: 'James Wilson',
    performed_at: '2026-01-27T14:00:00Z',
  },
  {
    id: '18',
    inventory_action: 'CLOCKOUT',
    item_id: 'item-018',
    item_name: 'Composition Books',
    product_id: 'prod-018',
    from_location_id: 'loc-h2',
    from_location_name: 'Shelf H2',
    to_location_id: 'loc-checkout',
    to_location_name: 'Checkout',
    quantity: 36,
    performed_by: 'user-005',
    user_name: 'Amanda Liu',
    note: 'Order #12343',
    performed_at: '2026-01-27T13:45:00Z',
  },
  {
    id: '19',
    inventory_action: 'MOVE',
    item_id: 'item-019',
    item_name: 'Colored Pencils (24ct)',
    product_id: 'prod-019',
    from_location_id: 'loc-d5',
    from_location_name: 'Bin D5',
    to_location_id: 'loc-e2',
    to_location_name: 'Shelf E2',
    quantity: 48,
    performed_by: 'user-002',
    user_name: 'Mike Johnson',
    performed_at: '2026-01-27T13:20:00Z',
  },
  {
    id: '20',
    inventory_action: 'ADJUSTMENT',
    item_id: 'item-020',
    item_name: 'Tape Dispensers',
    product_id: 'prod-020',
    from_location_id: 'loc-f3',
    from_location_name: 'Shelf F3',
    to_location_id: 'loc-f3',
    to_location_name: 'Shelf F3',
    quantity: 3,
    performed_by: 'user-003',
    user_name: 'Emily Rodriguez',
    note: 'Found missing units',
    performed_at: '2026-01-27T13:00:00Z',
  },
  {
    id: '21',
    inventory_action: 'ADD',
    item_id: 'item-021',
    item_name: 'Whiteboard Markers',
    product_id: 'prod-021',
    from_location_id: 'loc-supplier',
    from_location_name: 'Supplier Z',
    to_location_id: 'loc-c5',
    to_location_name: 'Bin C5',
    quantity: 72,
    performed_by: 'user-004',
    user_name: 'David Park',
    performed_at: '2026-01-27T12:30:00Z',
  },
  {
    id: '22',
    inventory_action: 'MOVE',
    item_id: 'item-022',
    item_name: 'Index Cards (3x5)',
    product_id: 'prod-022',
    from_location_id: 'loc-a4',
    from_location_name: 'Pallet 2',
    to_location_id: 'loc-b2',
    to_location_name: 'Shelf B2',
    quantity: 100,
    performed_by: 'user-001',
    user_name: 'Sarah Chen',
    performed_at: '2026-01-27T12:00:00Z',
  },
  {
    id: '23',
    inventory_action: 'CLOCKOUT',
    item_id: 'item-023',
    item_name: 'Watercolor Sets',
    product_id: 'prod-023',
    from_location_id: 'loc-g4',
    from_location_name: 'Shelf G4',
    to_location_id: 'loc-checkout',
    to_location_name: 'Checkout',
    quantity: 18,
    performed_by: 'user-005',
    user_name: 'Amanda Liu',
    note: 'Order #12342',
    performed_at: '2026-01-27T11:40:00Z',
  },
  {
    id: '24',
    inventory_action: 'DISCARD',
    item_id: 'item-024',
    item_name: 'Expired Glue Bottles',
    product_id: 'prod-024',
    from_location_id: 'loc-h3',
    from_location_name: 'Bin H3',
    to_location_id: 'loc-waste',
    to_location_name: 'Waste',
    quantity: 8,
    performed_by: 'user-006',
    user_name: 'James Wilson',
    note: 'Past expiration date',
    performed_at: '2026-01-27T11:15:00Z',
  },
  {
    id: '25',
    inventory_action: 'ADD',
    item_id: 'item-025',
    item_name: 'Staplers',
    product_id: 'prod-025',
    from_location_id: 'loc-receiving',
    from_location_name: 'Receiving',
    to_location_id: 'loc-d4',
    to_location_name: 'Shelf D4',
    quantity: 30,
    performed_by: 'user-002',
    user_name: 'Mike Johnson',
    performed_at: '2026-01-27T11:00:00Z',
  },
  {
    id: '26',
    inventory_action: 'MOVE',
    item_id: 'item-026',
    item_name: 'Protractors',
    product_id: 'prod-026',
    from_location_id: 'loc-e4',
    from_location_name: 'Bin E4',
    to_location_id: 'loc-f5',
    to_location_name: 'Shelf F5',
    quantity: 50,
    performed_by: 'user-003',
    user_name: 'Emily Rodriguez',
    performed_at: '2026-01-27T10:45:00Z',
  },
  {
    id: '27',
    inventory_action: 'ADJUSTMENT',
    item_id: 'item-027',
    item_name: 'Pencil Sharpeners',
    product_id: 'prod-027',
    from_location_id: 'loc-c3',
    from_location_name: 'Shelf C3',
    to_location_id: 'loc-c3',
    to_location_name: 'Shelf C3',
    quantity: -2,
    performed_by: 'user-004',
    user_name: 'David Park',
    note: 'Damaged units removed',
    performed_at: '2026-01-27T10:30:00Z',
  },
  {
    id: '28',
    inventory_action: 'CLOCKOUT',
    item_id: 'item-028',
    item_name: 'Graph Paper Pads',
    product_id: 'prod-028',
    from_location_id: 'loc-h5',
    from_location_name: 'Shelf H5',
    to_location_id: 'loc-checkout',
    to_location_name: 'Checkout',
    quantity: 24,
    performed_by: 'user-005',
    user_name: 'Amanda Liu',
    note: 'Order #12341',
    performed_at: '2026-01-27T10:15:00Z',
  },
  {
    id: '29',
    inventory_action: 'ADD',
    item_id: 'item-029',
    item_name: 'Calculator (Basic)',
    product_id: 'prod-029',
    from_location_id: 'loc-supplier',
    from_location_name: 'Supplier X',
    to_location_id: 'loc-g5',
    to_location_name: 'Bin G5',
    quantity: 40,
    performed_by: 'user-001',
    user_name: 'Sarah Chen',
    performed_at: '2026-01-27T10:00:00Z',
  },
  {
    id: '30',
    inventory_action: 'MOVE',
    item_id: 'item-030',
    item_name: 'Sticky Notes (3x3)',
    product_id: 'prod-030',
    from_location_id: 'loc-b5',
    from_location_name: 'Pallet 4',
    to_location_id: 'loc-c1',
    to_location_name: 'Shelf C1',
    quantity: 200,
    performed_by: 'user-006',
    user_name: 'James Wilson',
    performed_at: '2026-01-27T09:45:00Z',
  },
];
